-- Script để tạo bảng DETECTION_HISTORY trong database K_QMS_YHCT
-- Bảng này lưu lịch sử nhận diện tự động khuôn mặt

USE K_QMS_YHCT;
GO

-- Kiểm tra và xóa bảng cũ nếu tồn tại (CHỈ DÙNG KHI MUỐN RESET)
-- IF OBJECT_ID('dbo.DETECTION_HISTORY', 'U') IS NOT NULL
--     DROP TABLE dbo.DETECTION_HISTORY;
-- GO

-- Tạo bảng DETECTION_HISTORY
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DETECTION_HISTORY')
BEGIN
    CREATE TABLE dbo.DETECTION_HISTORY (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        MAYTE NVARCHAR(50) NOT NULL,
        PATIENT_NAME NVARCHAR(255) NULL,
        CONFIDENCE FLOAT NOT NULL DEFAULT 0,
        DETECTED_AT DATETIME NOT NULL DEFAULT GETDATE(),
        CAMERA_ID NVARCHAR(100) NULL,
        LOCATION NVARCHAR(255) NULL,
        SESSION_DATE DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
        NOTE NVARCHAR(500) NULL,
        
        -- Đảm bảo mỗi người chỉ được ghi nhận 1 lần mỗi ngày
        CONSTRAINT UQ_DETECTION_PER_DAY UNIQUE (MAYTE, SESSION_DATE)
    );
    
    -- Tạo index để query nhanh hơn
    CREATE NONCLUSTERED INDEX IX_DETECTION_HISTORY_SessionDate 
        ON dbo.DETECTION_HISTORY (SESSION_DATE DESC);
    
    CREATE NONCLUSTERED INDEX IX_DETECTION_HISTORY_MaYTe 
        ON dbo.DETECTION_HISTORY (MAYTE);
    
    CREATE NONCLUSTERED INDEX IX_DETECTION_HISTORY_DetectedAt 
        ON dbo.DETECTION_HISTORY (DETECTED_AT DESC);
    
    PRINT N'✅ Đã tạo bảng DETECTION_HISTORY thành công!';
END
ELSE
BEGIN
    PRINT N'⚠️ Bảng DETECTION_HISTORY đã tồn tại.';
END
GO

-- Hiển thị cấu trúc bảng
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DETECTION_HISTORY'
ORDER BY ORDINAL_POSITION;
GO

-- Kiểm tra unique constraint
SELECT 
    name AS ConstraintName,
    type_desc AS ConstraintType
FROM sys.objects 
WHERE parent_object_id = OBJECT_ID('DETECTION_HISTORY')
    AND type IN ('PK', 'UQ');
GO
